In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [6]:
learning_rate = 0.8
y = 0.95
num_episodes = 2000
rewards = []

In [7]:
for i in range(num_episodes):
    s = env.reset()
    rewards_episode = 0
    d = False
    j = 0
    while j < 99:
        j += 1
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1.0/(i+1)))
        s1, r, d, _ = env.step(a)
        Q[s,a] = Q[s,a] + learning_rate*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rewards_episode += r
        s = s1
        if d == True:
            break
            rewards.append(rewards_episode)

In [8]:
print("Score over time: " +  str(sum(rewards)/float(num_episodes)))
print("Final Q-Table Values")
print(Q)

Score over time: 0.0
Final Q-Table Values
[[2.35094573e-01 3.25063310e-03 2.95145459e-03 3.76659434e-03]
 [9.88605149e-04 5.24500506e-04 1.34501105e-03 1.54043622e-01]
 [9.98723172e-04 9.83924196e-04 9.47222292e-04 1.77832093e-01]
 [3.68042327e-04 9.41285421e-06 3.97575618e-05 4.78998504e-02]
 [4.06422687e-01 7.26822992e-04 7.02780443e-04 1.33247961e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.48139478e-04 1.82586542e-06 3.93634832e-04 3.18360124e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.65133277e-03 7.61437610e-04 1.05756400e-03 6.36344210e-01]
 [2.37977028e-04 6.70256576e-01 5.48062870e-04 0.00000000e+00]
 [3.70148285e-04 7.78298408e-01 1.16461853e-04 1.36065173e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.77682807e-01 2.40330602e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.95605919e-01]
 [0.00000000e